# Generated by Django 4.2.16 on 2024-11-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_options_alter_competence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
        migrations.AddField(
            model_name='slot',
            name='purpose',
            field=models.CharField(choices=[('aid', 'Pour aider'), ('request', 'Demande d’aide')], default='aid', max_length=10, verbose_name='Objectif'),
        ),
    ]
